void Save2OCDB(Char_t * det, Int_t runNumber=0) 
{
  // Save QA data generated by DataMaker into OCDB
  const char * kYear = "09" ; 
  // where ? 
  //IlcQA::SetQARefStorage(Form("%s%s/", IlcQA::GetQARefDefaultStorage(), kYear)) ;
  IlcQAv1::SetQARefStorage(Form("local://$ILC_ROOT/QAref/", det)) ;
  IlcQAv1::SetQARefDataDirName(IlcRecoParam::kLowMult) ; //Event Specie
  IlcQAManager *qam = IlcQAManager::QAManager("rec") ; 
  qam->Save2OCDB(runNumber, IlcRecoParam::kLowMult, kYear, det) ; 
}

