#ifdef __CINT__
  
#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;
  
#pragma link C++ class IlcJetHeader+;
#pragma link C++ class IlcUA1JetHeader+;
#pragma link C++ class IlcJetFinder+;
#pragma link C++ class IlcJetReaderHeader+;
#pragma link C++ class IlcJetESDReaderHeader+;
#pragma link C++ class IlcJetReader+;
#pragma link C++ class IlcJetESDReader+;
#pragma link C++ class IlcJetProductionData+;
#pragma link C++ class IlcUA1JetFinderV1+;
#pragma link C++ class IlcUA1JetFinderV2+;
#pragma link C++ class IlcUA1JetHeaderV1+;
#pragma link C++ class IlcCdfJetFinder+;
#pragma link C++ class IlcCdfJetHeader+;
#pragma link C++ class IlcJetGrid+;
#pragma link C++ class IlcJetUnitArray+;
#pragma link C++ class IlcJetHadronCorrection+; 
#pragma link C++ class IlcJetHadronCorrectionv0+;
#pragma link C++ class IlcJetHadronCorrectionv1+; 
#pragma link C++ class IlcJetFillUnitArray+;
#pragma link C++ class IlcJetESDFillUnitArrayTracks+;
#pragma link C++ class IlcJetESDFillUnitArrayEMCalDigits+;
#pragma link C++ class IlcJetAODFillUnitArrayTracks+;
#pragma link C++ class IlcJetAODFillUnitArrayEMCalDigits+;
#pragma link C++ class IlcJetDummyGeo+;
#pragma link C++ class IlcJetDummyShishKebabTrd1Module+;
#pragma link C++ class IlcAnalysisTaskJets+;
#pragma link C++ class IlcAnalysisTaskJetsCDF+;
#pragma link C++ class IlcDAJetFinder+;
#pragma link C++ class IlcDAJetHeader+;
#pragma link C++ class IlcJetAODReader+;
#pragma link C++ class IlcJetAODReaderHeader+;
#pragma link C++ class IlcJetKineReader;
#pragma	link C++ class IlcJetKineReaderHeader;
#pragma	link C++ class IlcJetMCReader;
#pragma	link C++ class IlcJetMCReaderHeader;
#pragma	link C++ class IlcJetHistos+;
#pragma	link C++ class IlcAnalysisTaskDiJets+;
#pragma	link C++ class IlcEventShape+;
#pragma	link C++ class IlcKMeansClustering+;
#pragma	link C++ class IlcKMeansResult+;
#pragma	link C++ class IlcAnalysisTaskKMeans+;
#pragma	link C++ class IlcAnalysisTaskFastEmbedding+;
#endif
